import type { INodeProperties } from 'n8n-workflow';

import { documentIdField, getManyFields, operationsFor } from './CommonDescription';

const NO_OF_EMPLOYEES_OPTIONS = [
	{ name: '1-10', value: '1-10' },
	{ name: '11-50', value: '11-50' },
	{ name: '51-200', value: '51-200' },
	{ name: '201-500', value: '201-500' },
	{ name: '501-1000', value: '501-1000' },
	{ name: '1000+', value: '1000+' },
];

/** `CRM Deal` fields. None is required API-side: Frappe infers the default status. */
const dealFields: INodeProperties[] = [
	{
		displayName: 'Annual Revenue',
		name: 'annual_revenue',
		type: 'number',
		default: 0,
		description: 'Annual revenue of the organization',
	},
	{
		displayName: 'Close Date',
		name: 'closed_date',
		type: 'dateTime',
		default: '',
		description: 'Actual closing date',
	},
	{
		displayName: 'Contact',
		name: 'contact',
		type: 'string',
		default: '',
		description: 'Link to a Contact doctype record',
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		default: '',
		description: 'Currency code, link to the Currency doctype (e.g. EUR, USD)',
	},
	{
		displayName: 'Deal Owner',
		name: 'deal_owner',
		type: 'string',
		default: '',
		description: 'Email of the user who owns the deal',
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'nom@email.com',
		default: '',
		description: 'Email address of the primary contact',
	},
	{
		displayName: 'Expected Closure Date',
		name: 'expected_closure_date',
		type: 'dateTime',
		default: '',
		description: 'Expected closing date',
	},
	{
		displayName: 'Expected Deal Value',
		name: 'expected_deal_value',
		type: 'number',
		default: 0,
		description: 'Expected value of the deal',
	},
	{
		displayName: 'First Name',
		name: 'first_name',
		type: 'string',
		default: '',
		description: 'First name of the primary contact',
	},
	{
		displayName: 'Industry',
		name: 'industry',
		type: 'string',
		default: '',
		description: 'Link to a CRM Industry doctype record',
	},
	{
		displayName: 'Job Title',
		name: 'job_title',
		type: 'string',
		default: '',
		description: 'Job title of the primary contact',
	},
	{
		displayName: 'Last Name',
		name: 'last_name',
		type: 'string',
		default: '',
		description: 'Last name of the primary contact',
	},
	{
		displayName: 'Lead',
		name: 'lead',
		type: 'string',
		default: '',
		description: 'Link to the originating CRM Lead, when the deal comes from a conversion',
	},
	{
		displayName: 'Lost Reason',
		name: 'lost_reason',
		type: 'string',
		default: '',
		description: 'Link to a CRM Lost Reason doctype record',
	},
	{
		displayName: 'Mobile Number',
		name: 'mobile_no',
		type: 'string',
		default: '',
		description: 'Mobile number of the primary contact',
	},
	{
		displayName: 'Next Step',
		name: 'next_step',
		type: 'string',
		default: '',
		description: 'Next planned action',
	},
	{
		displayName: 'Number of Employees',
		name: 'no_of_employees',
		type: 'options',
		options: NO_OF_EMPLOYEES_OPTIONS,
		default: '1-10',
		description: 'Employee count bracket of the organization',
	},
	{
		displayName: 'Organization',
		name: 'organization',
		type: 'string',
		default: '',
		description:
			'Link to a CRM Organization doctype record. This is the organization name, which doubles as its identifier.',
	},
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string',
		default: '',
		description: 'Landline phone number',
	},
	{
		displayName: 'Probability',
		name: 'probability',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0, maxValue: 100 },
		description: 'Probability of closing, as a percentage',
	},
	{
		displayName: 'Source',
		name: 'source',
		type: 'string',
		default: '',
		description: 'Link to a CRM Lead Source doctype record',
	},
	{
		displayName: 'Status',
		name: 'status',
		type: 'string',
		default: '',
		description:
			'Link to a CRM Deal Status doctype record (e.g. Qualification, Demo/Making, Negotiation, Won, Lost). Frappe applies the default status when left empty.',
	},
	{
		displayName: 'Territory',
		name: 'territory',
		type: 'string',
		default: '',
		description: 'Link to a CRM Territory doctype record',
	},
	{
		displayName: 'Website',
		name: 'website',
		type: 'string',
		default: '',
		description: 'Website of the organization',
	},
];

export const dealDescription: INodeProperties[] = [
	operationsFor('deal', 'deal'),
	documentIdField(
		'deal',
		'The Frappe record "name" field. For a deal it looks like CRM-DEAL-2026-00001.',
	),
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add field',
		default: {},
		displayOptions: { show: { resource: ['deal'], operation: ['create'] } },
		options: dealFields,
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add field',
		default: {},
		displayOptions: { show: { resource: ['deal'], operation: ['update'] } },
		options: dealFields,
	},
	...getManyFields('deal'),
];
