import type { INodeProperties } from 'n8n-workflow';

import { documentIdField, getManyFields, omitFields, operationsFor } from './CommonDescription';

/** `FCRM Note` fields. Only `title` is required. */
const noteFields: INodeProperties[] = [
	{
		displayName: 'Content',
		name: 'content',
		type: 'string',
		typeOptions: { rows: 5 },
		default: '',
		description: 'Body of the note, as HTML (a Text Editor field)',
	},
	{
		displayName: 'Reference Doctype',
		name: 'reference_doctype',
		type: 'options',
		options: [
			{ name: 'CRM Lead', value: 'CRM Lead' },
			{ name: 'CRM Deal', value: 'CRM Deal' },
		],
		default: 'CRM Lead',
		description: 'Record type the note is attached to',
	},
	{
		displayName: 'Reference Document Name',
		name: 'reference_docname',
		type: 'string',
		default: '',
		description:
			'Identifier of the attached record, for example CRM-DEAL-2026-00001. Set it together with "Reference Doctype".',
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		description: 'Title of the note',
	},
];

export const noteDescription: INodeProperties[] = [
	operationsFor('note', 'note'),
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['note'], operation: ['create'] } },
		description: 'Title of the note, the only field FCRM Note requires',
	},
	documentIdField(
		'note',
		'The Frappe record "name" field. FCRM Note uses a hash identifier generated by Frappe.',
	),
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add field',
		default: {},
		displayOptions: { show: { resource: ['note'], operation: ['create'] } },
		options: omitFields(noteFields, ['title']),
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add field',
		default: {},
		displayOptions: { show: { resource: ['note'], operation: ['update'] } },
		options: noteFields,
	},
	...getManyFields('note'),
];
